[profile.release]
overflow-checks = true

[profile.release.package."*"]
opt-level = 3

[profile.release.package."regex"]
opt-level = 0

[profile.release.package."regex-automata"]
opt-level = 0

[profile.release.package."aho-corasick"]
opt-level = 0

[net]
git-fetch-with-cli = true
