// PATH: src/app/layout.tsx
import type { Metadata } from 'next'
import './globals.css'
import Providers from './providers'
import { AppLayout } from '@/components/app-layout'
import React from 'react'

export const metadata: Metadata = {
    title: 'Anaheim',
    description: 'Generated by create-solana-dapp',
}

const links: { label: string; path: string }[] = [
    { label: 'Home', path: '/' },
    { label: 'Account', path: '/account' },
    { label: 'Stake & Mining', path: '/stake-mining' },
    { label: 'Posts', path: '/posts' },
    { label: 'Gemini-Helper', path: '/dev-helper' },
]

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang="en" suppressHydrationWarning>
        <body className="antialiased">
        <Providers>
            <AppLayout links={links}>{children}</AppLayout>
        </Providers>
        </body>
        </html>
    )
}

// Patch BigInt so we can log it using JSON.stringify without errors
declare global {
    interface BigInt {
        toJSON(): string
    }
}

BigInt.prototype.toJSON = function () {
    return this.toString()
}