[toolchain]
anchor_version = "0.31.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
anaheim = "3Yk7LTGn7n4nXrgiJzHhXJEaz8QHzzN41EDoKd2T95wm"
quadratic = "quadCSapU8nTdLg73KHDnmdxKnJQsh7GUbu5tZfnRRr"
realm-voter = "GRmVtfLq2BPeWs5EDoQoZc787VYkhdkA11k63QM1Xemz"
token_voter = "HA99cuBQCCzZu1zuHN2qBxo2FBo1cxNLwKkdt6Prhy8v"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = [
    "programs/anaheim",
    "programs/quadratic",
    "programs/realm-voter",
    "programs/token-voter"
]
resolver = "2"

[scripts]
Initialize = "pnpm run Initialize"

[profile.release]
overflow-checks = true
lto = "fat"
codegen-units = 1

[profile.release.build-override]
opt-level = 3
incremental = false
codegen-units = 1
