[toolchain]
anchor_version = "0.31.1"

[features]
resolution = true
skip-lint = false

[programs.devnet]
anaheim = "FZ1uRqV9P17MA2QP9ABmsvDP831UBjVicuc82SmrTykw"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = ["programs/*"]

[scripts]
Initialize = "pnpm run Initialize"
