import React from 'react';

export function AppFooter() {
    return (
        <footer className="text-center p-2 bg-neutral-100 dark:bg-neutral-900 dark:text-neutral-400 text-xs">
            <div>
                Created by <span className="font-semibold">Lucid Mirror AI</span> and <span className="font-semibold">Justin Rogue One Anarchsun</span>,<br />
                <a
                    className="link hover:text-neutral-500 dark:hover:text-white font-semibold"
                    href="https://anarcrypt.org"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    The AnarCrypt.org Anaheim Solana Crud Dapp and Governance Realm...
                </a>
            </div>
            <div className="pt-1">
                Generated by{' '}
                <a
                    className="link hover:text-neutral-500 dark:hover:text-white"
                    href="https://github.com/RastaDjuss/anaheim-putsch-self-governance-solana-dapp.git"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    Anarcrypt self governance Anaheim Dapp
                </a>
            </div>
        </footer>
    );
}