// src/utils/resolver/createSquelettes.ts

import fs from "fs";
import path from "path";

export async function createSquelettes(err: { symbol?: string; file?: string }) {
    if (!err.symbol) return { action: "ignore", reason: "no symbol" };
    const symbol = err.symbol;

    const file = err.file || `src/auto/${symbol}.ts`;
    const content = `// Auto-generated by resolver
export function ${symbol}(...args: any[]): void {
  throw new Error("Function ${symbol} not implemented");
}
`;

    const dir = path.dirname(file);
    if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
    fs.writeFileSync(file, content, { flag: "wx" }); // n’écrase pas si existe déjà

    return { action: "create_function", file, symbol };
}
